# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2025-02-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20250201_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
